# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.define "flockernode1" do |flockernode1| 
  	flockernode1.vm.box = "ubuntu/trusty64"
  	flockernode1.vm.network "public_network" , :adapter=>2 , type: "dhcp", :bridge => "eth0"
  	flockernode1.vm.hostname ="flockernode1"
  	flockernode1.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.name = "flockernode1"
     # Customize the amount of memory on the VM:
    vb.memory = "1024"
    end  
#    	flockernode1.vm.provision "chef_client" do |chef|
#     chef.chef_server_url = "https://api.chef.io/organizations/devops_testorg"
#     chef.validation_key_path = "devops_testorg-validator.pem"
#     chef.client_key_path  = "gauravjos.pem"
#     chef.validation_client_name = "devops_testorg-validator"
#     chef.flockernode_name = "flockernode1-lb"
#     # chef.add_flockernode = true
#  #   chef.cookbooks_path = "cookbooks"
# 	#chef.add_recipe  "apache2::default" 
# #	end
#   	end

 end
                                                                                                                                                                                                                                                                           
   config.vm.define "flockernode2" do |flockernode2| 
  	flockernode2.vm.box = "ubuntu/trusty64"
  	flockernode2.vm.network "public_network" , :adapter=>2 , type: "dhcp", :bridge => "eth0"
  	flockernode2.vm.hostname ="flockernode2"
  	flockernode2.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.name = "flockernode2"
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
   	end            
 #  	 flockernode2.vm.provision "chef_client" do |chef|
 #    	chef.chef_server_url = "https://api.chef.io/organizations/devops_testorg"
	#     chef.validation_key_path = "devops_testorg-validator.pem"
	#     chef.client_key_path  = "gauravjos.pem"
	#     chef.validation_client_name = "devops_testorg-validator"
	#     chef.flockernode_name = "flockernode2"
	#     # chef.add_flockernode = true
	#  #   chef.cookbooks_path = "cookbooks"
	# 	#chef.add_recipe  "apache2::default" 
	# #	end
 #  	end
  end
  
   config.vm.define "flockernode3" do |flockernode3| 
  	flockernode3.vm.box = "ubuntu/trusty64"
  	flockernode3.vm.network "public_network" , :adapter=>2 , type: "dhcp", :bridge => "eth0"
  	flockernode3.vm.hostname ="flockernode3"
  	flockernode3.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.name = "flockernode3"
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
   end            
#    flockernode3.vm.provision "chef_client" do |chef|
#     chef.chef_server_url = "https://api.chef.io/organizations/devops_testorg"
#     chef.validation_key_path = "devops_testorg-validator.pem"
#     chef.client_key_path  = "gauravjos.pem"
#     chef.validation_client_name = "devops_testorg-validator"
#     chef.flockernode_name = "flockernode3"
#     # chef.add_flockernode = true
#  #   chef.cookbooks_path = "cookbooks"
# 	#chef.add_recipe  "apache2::default" 
# #	end
#   	end
  end


   #config.vm.define "mydb" do |mydb| 
  #	mydb.vm.box = "ubuntu/trusty64"
  #	mydb.vm.network "public_network"
  #	mydb.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
  #  vb.gui = true
  #  vb.name = "mydb"
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end            
   # mydb.vm.provision "chef_client" do |chef|
   #  chef.chef_server_url = "https://api.chef.io/organizations/devops_testorg"
   #  chef.validation_key_path = "devops_testorg-validator.pem"
   #  chef.client_key_path  = "gauravjos.pem"
   #  chef.validation_client_name = "devops_testorg-validator"
   #  chef.flockernode_name = "mydb"
   #  # chef.add_flockernode = true
  	# end
  #end
end
